version: '2'
services:
  starter03-app:
    image: starter03
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://starter03-postgresql:5432/starter03
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  starter03-postgresql:
    extends:
      file: postgresql.yml
      service: starter03-postgresql
